### ISSUE TITLE
Writing TIF with less than 5 slices in stack adds one more dimension

### ISSUE THREAD

**Issue by ximeg** [cgohlke/tifffile#100]
I believe I discovered a bug. I work with 3D hyperstacks and want to save a stack into a TIF file. If my stack contains five or more slices, the saved image has three dimensions as the source stack. However, if the number of slices is less than five, the saved image gets an additional dimension and becomes a 4D stack.

Below is the MWE:
```python
import dask.array as da
from dask_image import imread
from skimage import io

# This works as expected
ar = da.zeros([5, 20, 20])
io.imsave("test.tif", ar)
imread.imread('test.tif').shape
##  Out: (5, 20, 20)

# This produces an unexpected extra dimension
ar = da.zeros([4, 20, 20])
io.imsave("test.tif", ar)
imread.imread('test.tif').shape
## Out: (1, 4, 20, 20)
```

I tried to supply `shape` argument to the tif writer, but it did not make any difference. 

I installed `tifffile` today using Anaconda, here is the version I have:
```
import tifffile
tifffile.__version__
# Out: '2019.7.26.2'
```

**Comment by cgohlke** [comment]
The additional dimension does not come from tifffile. 

To solve the issue, specify the color space of the data (`photometric='minisblack'`) to get consistent storage. Otherwise tifffile stores the (4, 20, 20) array as planar RGBA. This behavior is deprecated in newer versions of tifffile. A DeprecationWarning is currently issued.
