### ISSUE TITLE
Parse entries of type "time" in metaseries_metadata

### ISSUE THREAD

**Issue by anntzer** [cgohlke/tifffile#143]
Currently, entries of type "time" in metaseries_metadata are reported as strings (i.e., "as is").  They could be parsed into datetime objects for easier downstream use.  AFAICT (admittedly from a single instrument...), the correct strptime format for the parsing is `"%Y%m%d %H:%M:%S.%f"`.  Thoughts?

**Comment by cgohlke** [comment]
I think that's reasonable and easy to implement. It will be added to the next version.

**Comment by anntzer** [comment]
Sorry for not realizing this earlier, but it turns out that the datetime format is a bit of a mess.  The TIFF 6.0 spec actually states that the format must be "YYYY:MM:DD HH:MM:SS" (in the format given in the spec), but as you can see above the format I've seen in my files (Metamorph) is different (no colon separators in yearmonthdate, milliseconds are also given).

I had a look into the source of bioformats and they actually try a bunch of different formats until one works; see https://github.com/ome/bioformats/blob/1cf1fefa364e19c8fb8e81d6cda0824f353dc4df/components/formats-bsd/src/loci/formats/in/BaseTiffReader.java#L431 and https://github.com/ome/bioformats/blob/1cf1fefa364e19c8fb8e81d6cda0824f353dc4df/components/formats-bsd/src/loci/formats/in/BaseTiffReader.java#L75-L82 (these are Joda formats, see https://www.joda.org/joda-time/apidocs/org/joda/time/format/DateTimeFormat.html).

**Comment by cgohlke** [comment]
I understood that this issue is about parsing the "time" types in the `ImageDescription` tag of MetaSeries files. The time format seems to be always "%Y%m%d %H:%M:%S.%f" and I think it makes sense to parse "time" types to `datetime` objects in the `metaseries_description_metadata` function. 

The TIFF spec on the other hand defines the value of the `DateTime` tag to be a string in "YYYY:MM:DD HH:MM:SS" format. That spec doesn't apply to above MetaSeries metadata.

The `TiffFile.metaseries_metadata` property should probably be removed at some point. The metaseries metadata is really a per page property.

**Comment by anntzer** [comment]
Ah, sorry for the false alert, I got these two types of time metadata confused.  Forget my second message, then :)

**Comment by cgohlke** [comment]
Fixed in v2022.7.28.

**Comment by cgohlke** [comment]
v2022.8.3 includes a `strptime` function that parses common datetime formats.
