### ISSUE TITLE
Tags Not In Ascending Order

### ISSUE THREAD

**Issue by John-P** [cgohlke/tifffile#171]
I keep getting the following warning from libtiff when reading files written by tifffile:

```
TIFFReadDirectoryCheckOrder: Warning, Invalid TIFF directory; tags are not sorted in ascending order.
```

Looking at the TIFF spec it does say this:

> Sort Order
>
> The entries in an IFD must be sorted in ascending order by Tag. Note that this is not the order 
> in which the fields are described in this document. The Values to which directory entries point 
> need not be in any particular order in the file.

Is there a way to ensure the tags are in the correct order?

**Comment by cgohlke** [comment]
That's a known issue with multiple tags having the same code.

https://github.com/cgohlke/tifffile/blob/a73812e98f58b068a590de862ed547820fd332ad/tifffile/tifffile.py#L2881-L2884

Tifffile does write the tags in ascending order. The issue seems to be with [libtiff not handling this case correctly](https://gitlab.com/libtiff/libtiff/-/blob/master/libtiff/tif_dirread.c#L4687-4704).

**Comment by cgohlke** [comment]
As a workaround, check which tags of the same code are written twice and see if  it can be avoided. Usually it is the `ImageDescription` tag when the user provides a `description` and not disabling `metadata`. Try `imwrite(..., description='...', metadata=None)`.

**Comment by cgohlke** [comment]
I opened a [pull request for libtiff ](https://gitlab.com/libtiff/libtiff/-/merge_requests/432).

**Comment by cgohlke** [comment]
Looks like the libtiff authors are not going to fix the issue and you have to specifically silence the warning in all libtiff based readers. .
