### ISSUE TITLE
side effect with series property

### ISSUE THREAD

**Issue by christianrickert** [cgohlke/tifffile#179]
Hi Christoph,

I might've run into the side effect with the `def series(self) -> list[TiffPageSeries]` function mentioned here:
https://github.com/cgohlke/tifffile/blob/08290c7ae44a4248f64d7cd0e74361f570f56e79/tifffile/tifffile.py#L4267
There was no further details, so you might not have had the time to have a closer look. Here's what I found:
Accessing the `serie.pages` property triggers the side effect starting with the **_second_** (and any further) file in my list of files:
```Python
with tifff.TiffFile(file) as tif:
    for serie in tif.series:  # no problem
        print(serie.name)
        for page in serie.pages:  # triggers side effect for consecutive files
            print(page)
            """
            TiffPage 0
            TiffPage 1
            TiffFrame 2
            ...
            """
```
I didn't find a way to access the `page.tags` for the `TiffFrame`, which is actually a `TiffPage` as far as I understand.
My current workaround is to get `len(serie)` and assign the `tif.pages` to the individual series entries by count.

Best regards,
Chris

**Comment by cgohlke** [comment]
Not sure I understand the issue. Can you add more details of what kind of files you have. Is it an OME-TIFF multi-file series? You mention that the issue does not happen with the first file, but the code does not iterate over files. Is the issue that after opening a file with `TiffFile`, opening a second file with `TiffFile` somehow behaves different than expected? The `TiffFile` instances should be independent.

The possible side effect of accessing `TiffFile.series` is that iterating over `TiffFile.pages` behaves differently before and after accessing `TiffFile.series`. It doesn't sound like what you are describing.

`TiffFile.pages` and `TiffPageSeries.pages` may contain instances of `TiffPage` and `TiffFrame`. `TiffPage` has a `tags` property, `TiffFrame` does not. To get a `TiffPage` instance of a `TiffFrame`, call `TiffFrame.aspage`. That is not possible for all frames though. `TiffPageSeries.pages` typically contain only one (or few) `TiffPage` instances since all pages/frames in a series are assumed to share the same properties. What is the use case for iterating over `TiffPageSeries.pages` to read tags?

**Comment by christianrickert** [comment]
I wrote a small Python script that reads out all metadata (`tags`) and writes them into a JSON-formatted text file to document experimental conditions: We use various TIFF formats in our lab - custom TIFFs, MIBITIFF, and QPTIFF (PerkinElmer/Akoya) mostly.
To write out all metadata, I load a specific TIFF file, then loop over the series (if available), then the pages, then read the tags, and finally write out a single metadata dictionary with the `json` module.
Your `tifffile` module works great to extract the `tags` and is satisfyingly fast.

The issue occurred when I had made a code change (see below) and suddenly observed `TiffFrame`s instead of `TiffPage`s (two pages followed by the remaining pages as frames). Since I didn't know what was going on, I looked into your source code and saw the comment about the side effect: Your description was very brief, which lead me to belief that you might've run into this issue - without having the time to "dig deeper" and identify the actual culprit.
I couldn't reproduce the issue by simply accessing the `series` as in calling `TiffFile.series`, for example when printing out the `name` property of a series element in a loop. Instead, the issue only occurred when I accessed the `page` property of individual `Tiff.series` elements.

Please let me know if my description is lacking clarity. - I have worked around the issue, so please feel free to disregard my issue altogether: it's not a "call to arms" - I wanted to share my observations with you in the hope that you might find them useful.

**Comment by cgohlke** [comment]
Got it. It may be surprising and inconvenient in your use specific case, but it is by design that the `pages` properties contain `TiffPage` and `TiffFrame` instances, or even `None` for missing data. 

The type annotations also make this clear. For example, mypy reports two problems with `TiffFile('test.tif').series[0].pages[0].tags`: 
 - `Item "TiffFrame" of "Union[TiffPage, TiffFrame, None]" has no attribute "tags"  [union-attr]`
 - `Item "None" of "Union[TiffPage, TiffFrame, None]" has no attribute "tags"  [union-attr]`

Instead, the code should be:
```
page = tifffile.TiffFile('temp.tif').series[0].pages[0]
if page is not None:
    try:
        page.aspage().tags
    except ValueError:
        # e.g., virtual frame, which has no IFD structure in the file
        ...
```
