### ISSUE TITLE
Tiff stack save error

### ISSUE THREAD

**Issue by Mona-MengLi** [cgohlke/tifffile#180]
When saving tiff stacks (gray scale frames stacked in tiff format), the saved file could not be read by tifffile correctly in python. The error message is "ValueError: not enough values to unpack (expected 3, got 2)". I need to open the file in image browser such as FIJI, save it as tiff, then load the new saved file. I guess there' s something wrong in the format of the saved tiff stack?

**Comment by Mona-MengLi** [comment]
Here is a sample file to test.

**Comment by cgohlke** [comment]
Thank you. The test file didn't get through but the issue is clear now.

`tifffile.imwrite` by default writes additional metadata identifying the shape of the written numpy array, and `tifffile.imread` uses that metadata to return just that numpy array from the file by default.

Consider one of the following options:

1. Do not append to existing files, which is very inefficient. Instead, use `tifffile.imwrite(fileout, vid)` to rewrite the video array at once, or:

```python
with tifffile.TiffWriter(fileout) as tif:
    for frame in vid:
        tif.write(frame, contiguous=True)
```

2. Instruct tifffile not to write additional metadata: `tifffile.imwrite(..., metadata=False)`
3. Instruct tifffile not to use the metadata when reading: `tifffile.imread(fileout, is_shaped=False)`

**Comment by Mona-MengLi** [comment]
Thanks! It works!
