### ISSUE TITLE
Add `asdask` to imread

### ISSUE THREAD

**Issue by gatoniel** [cgohlke/tifffile#183]
Hi, in recent times I started using `tifffile` with quite big tif-files that take long to load into memory entirely. As I often only require small parts of the tif-files at a time, I am using the following convenience wrapper to load the tif-files as `dask` arrays.
```python
import dask.array as da
from tifffile import imread


def tif_to_dask(filename):
    return da.from_zarr(
        imread(filename, aszarr=True)
    )
```
However, it would be even more convenient if the `tifffile.imread` function would have a `asdask` flag, such that one can directly read in tifffiles as `dask` array. For example, I would like to do this:
```python
from tifffile import imread

dask_img = imread(filename, asdask=True)
```
Best,
Niklas

**Comment by cgohlke** [comment]
Thanks for the suggestion. I previously decided not implement this feature for the following reasons:

1. `ZarrStore` instances need to be closed. Otherwise they might leak open file handles. Neither Zarr not dask arrays can do that (AFAIK).
2. `ZarrStore` instances give you the option to open them as Zarr or dask arrays, or export to fsspec reference files.
3. Typing the imread function becomes overly complicated. It is already not satisfactory.
4. Avoid direct dependencies on zarr and dask.
