### ISSUE TITLE
Feature request. Read a patch

### ISSUE THREAD

**Issue by cardo-correrdor** [cgohlke/tifffile#200]
It would be convenient to pass to imread() the box coordinates of the patch to read. So not to read the whole image and extract patch after that but read directly the patch. If the patching is available on the lower level, than it should save some time.

**Comment by cgohlke** [comment]
Sorry I have missed this issue until now.

The feature is easy to add through the existing Zarr interface. The next version of tifffile will add a `selection` parameter, which is internally used to index a Zarr array...

However, I am not sure the feature is that useful:

- There are already parameters that allow selection of data subsets in the file, e.g. `key`, `series`, and `level`.
- It is of limited use without knowing the image axes or shape, which may have many dimensions.
- It creates a direct dependency on Zarr.
- The overhead of reading through Zarr can be significant since TIFF segments are often very small.
- Obtaining a Zarr store instead through the existing API enables many options such as caching and the use of dask for parallel reading of segments/files.
- The approach will not work well for some TIFF formats such as ImageJ hyperstacks, which store image data as a single contiguous chunk instead of smaller segments.

**Comment by agrouaze** [comment]
Hello @cgohlke ,
thanks for your answer,
I am not sure to understand whether you want to add this feature or not in the end.
On the question of usefulness, I am confident about it, especially for very large tiff files.
you mention "There are already parameters that allow selection of data subsets in the file, e.g. key, series, and level."
Can you post an example to do such sub-settting/slicing using only metadata of the tiff file and before any load in memory of the full image?

**Comment by cgohlke** [comment]
Fixed in v2023.7.4.
