### ISSUE TITLE
suggest using os.sched_getaffinity instead of os.cpu_count when available to set MAXWORKERS and MAXIOWORKERS

### ISSUE THREAD

**Issue by jmuhlich** [cgohlke/tifffile#231]
The default value for MAXWORKERS and MAXIOWORKERS is currently based on `os.cpu_count()` which provides the number of _physically installed_ CPUs. In some contexts only _some_ of those CPUs are actually available to a process, such as when an HPC cluster schedules each job on one or more specific dedicated cores. In fact the problem can be quite severe on high-core-count systems when a process is locked to a single CPU; 32 threads all fighting for the same core really slows things down.

Under Linux at least, in these cases `len(os.sched_getaffinity(0))` can be used to get the available CPU count. The typical approach is to use the `sched_getaffinity` method if that function is defined, otherwise fall back to `cpu_count`.

**Comment by cgohlke** [comment]
Thank you. Sounds good, This will be in the next version.

The maximum number of default threads/workers should probably also be limited to 32 in accordance with concurrent.futures since Python 3.8.

The default number of threads can be can limited (since 2023.7.18) by the setting the `TIFFFILE_NUM_THREADS` and `TIFFFILE_NUM_IOTHREADS` environment variables . See #215.
