### ISSUE TITLE
Saving a 4D array where one of the dimensions is 3 or 4 moves that axis as last

### ISSUE THREAD

**Issue by ElpadoCan** [cgohlke/tifffile#235]
When I do the following 

```python
from tifffile import imwrite
import numpy as np

import skimage.io

image = np.zeros((10, 4, 100, 100), dtype='uint16')

imwrite(
    'test.tif', 
    image, 
    # photometric='minisblack'
)

read_image = skimage.io.imread('test.tif')
print(image.shape)
```

It prints 
```
(10, 100, 100, 4)
```

Which means the axis with size 4 was moved to the end.

**Comment by ElpadoCan** [comment]
Actually, I didn't solve by upgrading tifffile, but by using `tifffile.imread` instead of `skimage.io.imread`. Since it seems to be a skimage problem I keep this closed and try to understand the situation on skimage issues

**Comment by cgohlke** [comment]
Looks like a duplicate of #196 . See also https://github.com/scikit-image/scikit-image/issues/5242.

**Comment by ElpadoCan** [comment]
Yeah, I saw that one, but it does not fix skimage.io.imread :D 

I don't get the rationale of moving axis around. If I save to numpy file and read from numpy file I get what I saved. It's quite annoying behaviour

**Comment by cgohlke** [comment]
The rational is that [skimage.io.imread](https://scikit-image.org/docs/stable/api/skimage.io.html#skimage.io.imread) is documented to return RGB components/samples in the last dimension. However, since imread does not have access to TIFF internals and numpy arrays do not carry any metadata, imread uses heuristics to determine planar storage, which cannot work in many cases. The solution is not to use skimage.io. 
Another point of view is that tifffile was originally designed to store and retrieve any-dimensional numpy arrays to/from TIFF, skimage.io is meant to deal with images.

**Comment by ElpadoCan** [comment]
Interesting thank you for your answer. I guess that what deceived me was that skimage claims they use tifffile internally for tif files and I thought I was basically using the same function. Anyway, I replaced skimage.io.imread in those million places where my code uses it and life is good again :D. Plus I will never use skimage to read tif files anymore in my life 😂. Thank you again!
