### ISSUE TITLE
Remove Specific Level

### ISSUE THREAD

**Issue by alexlsa** [cgohlke/tifffile#248]
Hi,

I have `.tif` image with ten pyramid layers, how can I remove specif pyramid level from this tif ? For example I want to remove 4. level but I do not want to decompress/compress tif image

Actually I can do this operation loading tif image but this is time consuming and also require decompress and compress again

Thank you

**Comment by cgohlke** [comment]
There is no high-level API in tifffile to remove specific pyramid levels.

Try to rewrite the file without specific levels by copying compressed segments verbatim. That is tedious and might not work for all formats (e.g. NDPI). See for example: https://github.com/cgohlke/tifffile/blob/2b5a5208008594976d4627bcf01355fc08837592/tests/test_tifffile.py#L18606-L18671

[Tifftools](https://github.com/DigitalSlideArchive/tifftools) could also be an option.

It might work to patch IFD offsets in order to skip specific levels in the TIFF IFD chain, which is a linked list. The details depend on the format of the file.
