### ISSUE TITLE
Writing shaped series of ome tiff seems broken since version 2024.8.24

### ISSUE THREAD

**Issue by markbader** [cgohlke/tifffile#270]
Hi, I am trying to write a numpy array to an ome tiff file. With the script:

```python
import numpy as np
from tifffile import imwrite

image = np.random.rand(50, 500, 500, 1)

imwrite(
    "image.ome.tiff",
    image,
    ome=True,
    metadata={
        "axes": "ZYXC",
    },
)
```

This worked until version 2024.8.10, but fails in recent versions with `ValueError: shape does not match stored shape`.

It seems that the `write` method of the `TiffWriter` class is responsible for the changed behavior, while this loop:
```python
while len(shape) > 2 and shape[-1] == 1:
    shape = shape[:-1]  # remove trailing 1s
```
 was executed for all shaped series, it is now only executed if `self._tifffile` is `True`. It would be great if you could explain why this change in behavior happened, or how I can achieve the same with recent versions.

**Comment by cgohlke** [comment]
> explain why this change in behavior happened

The breaking change was necessary in order to write width-1 dimensions to OME-TIFF. It is also more consistent with the read behavior (no S=1 dimension). The self._tifffile mode is special, because it's metadata can describe any shape (OME can't) and it optimizes for most efficient storage by default. Finally, the metadata axes are just for the writer to label dimensions in the OME-XML. It is not used to control how the image is stored in TIFF, but it must be compatible with that.

> how I can achieve the same with recent versions

Drop the last dimension:
```python
image = np.random.rand(50, 500, 500)

imwrite("image.ome.tiff", image, ome=True, metadata={"axes": "ZYX"})
```
