### ISSUE TITLE
Bug: zarr arrays cannot be pickled

### ISSUE THREAD

**Issue by ieivanov** [cgohlke/tifffile#64]
zarr arrays created with `tifffile` cannot be pickled. This prevents using zarr arrays in multiprocessing applications.

Running:
```python
zarr_store = tifffile.imread('path_to_data', aszarr=True)
zarrArray = zarr.open(zarr_store, mode='r')
pickle.dumps(zarrArray)
```
throws the error:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-343d376ee953> in <module>
----> 1 pickle.dumps(zarrArray)

AttributeError: Can't pickle local object 'TIFF.CHUNKMODE.<locals>.CHUNKMODE'
```

I believe this is caused by this part of the code: https://github.com/cgohlke/tifffile/blob/d2fe871da182acc45f54b5a03bcf29a0b52a32ae/tifffile/tifffile.py#L12454-L12461 and can be solved using `functools.wraps` as described here: http://gael-varoquaux.info/programming/decoration-in-python-done-right-decorating-and-pickling.html

**Comment by cgohlke** [comment]
This is a known limitation (see discussion at https://github.com/AllenCellModeling/aicsimageio/issues/178#issuecomment-760713882) but I don't think it's a bug since zarr does not strictly require stores to be picklable (https://github.com/zarr-developers/zarr-python/blob/master/docs/tutorial.rst#pickle-support). I think aicsimageio works around this limitation by opening a new ZarrFileStore in each process.
Fundamentally, tifffile.ZarrFileStore is not picklable because it uses a TiffFile instance, which uses system handles (file handles and threads). To make tifffile.ZarrFileStore picklable would need a different approach outlined in https://github.com/AllenCellModeling/aicsimageio/issues/178#issuecomment-761166549.  However I expect that to be significantly slower than the current implementation, both in initialization and chunk access.

**Comment by joshmoore** [comment]
@ieivanov, the [zarr.convenience.copy_store](https://zarr.readthedocs.io/en/stable/api/convenience.html?highlight=convenience#zarr.convenience.copy_store) helper method may do what you want. It won't produce pickled data, but it should convert the data from TIFF to Zarr on disk for later re-use.
